name: Deploy to Development

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy-development:
    name: Deploy development
    environment: development
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build & tag docker image
        uses: AplinkosMinisterija/reusable-workflows/.github/actions/docker-build-tag-push@main
        with:
          environment: development
          push: true

      - name: Trigger deploy
        uses: AplinkosMinisterija/reusable-workflows/.github/actions/trigger-workflow-and-wait@main
        with:
          application-id: ${{ secrets.SPORTO_REGISTRAS_TRIGGER_DEPLOY_APPLICATION_ID }}
          application-private-key: ${{ secrets.SPORTO_REGISTRAS_TRIGGER_DEPLOY_APPLICATION_PRIVATE_KEY }}
          repository: ${{ secrets.SPORTO_REGISTRAS_TRIGGER_DEPLOY_REPOSITORY }}
          workflow-file-name: ${{ secrets.SPORTO_REGISTRAS_TRIGGER_DEPLOY_WORKFLOW_FILE_NAME }}
          workflow-payload: '{"environment": "development"}'
